### ISSUE TITLE
Ignoring repeated constraints

### ISSUE THREAD

**Issue by dmikhalin** [typedb/typeql#281]
## Problem to Solve

It seems that current `typeql-rust` ignores repeated constraints, but we have this scenario in BDD: https://github.com/vaticle/typedb-behaviour/blob/7675fefe3f3b555ce9db558fda27d5ac2314fb17/typeql/language/define.feature#L1263

## Proposed Solution

Fix `typeql-rust` parser behaviour to make it consistent with `java` parser.
This scenario is temporarily ignored.

**Comment by farost** [comment]
It is a valid behavior in 3.0, so I am closing this issue with the updated and extended BDD tests.
